import tkinter as tk
ventana= tk.Tk()
ventana.title("Datos del usuario")
ventana.geometry("350x200")
etiqueta=tk.Label(ventana,text="Nombre y apellido",font=("arial",15))
etiqueta.pack(pady=10)
entrada= tk.Entry(ventana,font=("Arial",10))
entrada.pack(pady=10)
entrada2= tk.Entry(ventana,font=("Arial",10))
entrada2.pack(pady=5)
etiqueta_final=tk.Label(ventana,text="",font=("Arial",12),fg="red")
etiqueta_final.pack(pady=5)
def mostra_texto ():
    texto=entrada.get()
    texto2=entrada2.get()
    etiqueta_final.config(text=texto+""+texto2)
boton=tk.Button(ventana,text="Mostrar Datos",command=mostra_texto)
boton.pack(pady=10)
ventana.mainloop()